bluesky-project:
  nameOverride: bluesky-cloud-admin-server
  image:
    artifactId: bluesky-cloud-admin-server
  service:
    port: 30102
    nodePort: 30102
  ingress:
    enabled: true
    hosts:
    - host: admin.cloud.bluesky.local
      paths:
      - path: /
        pathType: Prefix