apiVersion: v1
kind: ConfigMap
metadata:
  name: seaweedfs-s3-config
data:
  s3.json: |
    {
      "identities": [
        {
          "name": "tempo",
          "credentials": [
            {
              "accessKey": "seaweedfs_access_key",
              "secretKey": "seaweedfs_secret_key"
            }
          ],
          "actions": [
            "Admin",
            "Read",
            "Write"
          ]
        }
      ]
    }
