apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-deployment
  labels:
    app: seaweedfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs
  template:
    metadata:
      labels:
        app: seaweedfs
    spec:
      containers:
        - name: seaweedfs
          image: chrislusf/seaweedfs:latest
          args:
            - server
            - -s3
            - -dir=/data
            - -s3.config=/etc/seaweedfs/s3.json
          ports:
            - containerPort: 8333
            - containerPort: 9333
          volumeMounts:
            - name: seaweedfs-data
              mountPath: /data
            - name: seaweedfs-config
              mountPath: /etc/seaweedfs
      volumes:
        - name: seaweedfs-data
          persistentVolumeClaim:
            claimName: seaweedfs-data-pvc
        - name: seaweedfs-config
          configMap:
            name: seaweedfs-s3-config
