
replicaCount: 1

springProfilesActive: k8sdev

image:
  host: nexus.bluesky.local:8083
  artifactId: bluesky-web-gate
  buildVersion: 0.0.1-SNAPSHOT
  buildNumber: 175
  
imagePullSecrets:
 - name: regcred
nameOverride: ""
  
service:
  type: NodePort
  port: 30122
  nodePort: 30122
  
  
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 10
  periodSeconds: 3
  failureThreshold: 60
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  
resources: {}