
replicaCount: 1

springProfilesActive: k8sdev

image:
  host:
  artifactId: 
  buildVersion: 
  buildNumber: 
  
imagePullSecrets:
 - name: regcred
nameOverride: ""
  
service:
  type: NodePort
  port: 
  nodePort: 
  
  
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 10
  periodSeconds: 3
  failureThreshold: 60
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 5

ingress:
	enabled: true
	hosts:
	  - path: /
	    pathType: Prefix


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  
resources: {}