apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "bluesky-project.name" . }}
  name: {{ include "bluesky-project.name" . }}-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "bluesky-project.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "bluesky-project.name" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: spring
          args:
            - '--spring.profiles.active={{ .Values.springProfilesActive }}'
            - '--spring.application.name={{ include "bluesky-project.name" . }}'
          workingDir: /usr/local/app
          image: '{{ .Values.image.host }}/luversof/{{ .Values.image.artifactId}}:{{ .Values.image.buildVersion }}.{{ .Values.image.buildNumber }}'
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          ports:
            - name : http
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
