apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "bluesky-project.name" . }}
    spring-boot: 'true'
  name: {{ include "bluesky-project.name" . }}-service
  namespace: default
spec:
  ports:
    - name : http
      nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    app: {{ include "bluesky-project.name" . }}
  type: {{ .Values.service.port }}