PersistentVolume:
  sonarqubeData:
    hostPath:
      path: /mnt/c/data/sonarqube-data
  sonarqubeLogs:
    hostPath:
      path: /mnt/c/data/sonarqube-logs
  sonarqubeExtensions:
    hostPath:
      path: /mnt/c/data/sonarqube-extensions