apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mssql
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: opensource/mssql
    repoURL: 'https://github.com/luversof/bluesky-argocd-applications.git'
    targetRevision: develop
    helm:
      valueFiles:
        - values-work.yaml
  sources: []
  project: default
