apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-cloud-netflix-eureka-server-1
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: bluesky-project_subchart
    repoURL: 'https://github.com/luversof/bluesky-argocd-applications.git'
    targetRevision: develop
    helm:
      valueFiles:
        - subchart/bluesky-cloud-netflix-eureka-server-1/values.yaml
        - subchart_home/buildInfo-bluesky-cloud/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-cloud-netflix-eureka-server-2
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: bluesky-project_subchart
    repoURL: 'https://github.com/luversof/bluesky-argocd-applications.git'
    targetRevision: develop
    helm:
      valueFiles:
        - subchart/bluesky-cloud-netflix-eureka-server-2/values.yaml
        - subchart_home/buildInfo-bluesky-cloud/values.yaml
  sources: []
  project: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-cloud-admin-server
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: bluesky-project_subchart
    repoURL: 'https://github.com/luversof/bluesky-argocd-applications.git'
    targetRevision: develop
    helm:
      valueFiles:
        - subchart/bluesky-cloud-admin-server/values.yaml
        - subchart_home/buildInfo-bluesky-cloud/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-cloud-config-server
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: bluesky-project_subchart
    repoURL: 'https://github.com/luversof/bluesky-argocd-applications.git'
    targetRevision: develop
    helm:
      valueFiles:
        - subchart/bluesky-cloud-config-server/values.yaml
        - subchart_home/buildInfo-bluesky-cloud/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-cloud-gateway
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: bluesky-project_subchart
    repoURL: 'https://github.com/luversof/bluesky-argocd-applications.git'
    targetRevision: develop
    helm:
      valueFiles:
        - subchart/bluesky-cloud-gateway/values.yaml
        - subchart_home/buildInfo-bluesky-cloud/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-api-blog
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: bluesky-project_subchart
    repoURL: 'https://github.com/luversof/bluesky-argocd-applications.git'
    targetRevision: develop
    helm:
      valueFiles:
        - subchart/bluesky-api-blog/values.yaml
        - subchart_home/buildInfo-bluesky-project/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-api-board
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: bluesky-project_subchart
    repoURL: 'https://github.com/luversof/bluesky-argocd-applications.git'
    targetRevision: develop
    helm:
      valueFiles:
        - subchart/bluesky-api-board/values.yaml
        - subchart_home/buildInfo-bluesky-project/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-api-bookkeeping
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: bluesky-project_subchart
    repoURL: 'https://github.com/luversof/bluesky-argocd-applications.git'
    targetRevision: develop
    helm:
      valueFiles:
        - subchart/bluesky-api-bookkeeping/values.yaml
        - subchart_home/buildInfo-bluesky-project/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-api-user
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: bluesky-project_subchart
    repoURL: 'https://github.com/luversof/bluesky-argocd-applications.git'
    targetRevision: develop
    helm:
      valueFiles:
        - subchart/bluesky-api-user/values.yaml
        - subchart_home/buildInfo-bluesky-project/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-web-gate
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: bluesky-project_subchart
    repoURL: 'https://github.com/luversof/bluesky-argocd-applications.git'
    targetRevision: develop
    helm:
      valueFiles:
        - subchart/bluesky-web-gate/values.yaml
        - subchart_home/buildInfo-bluesky-project/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluesky-web-swagger-ui
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: bluesky-project_subchart
    repoURL: 'https://github.com/luversof/bluesky-argocd-applications.git'
    targetRevision: develop
    helm:
      valueFiles:
        - subchart/bluesky-web-swagger-ui/values.yaml
        - subchart_home/buildInfo-bluesky-project/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
