apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-data-pv
  labels:
    app: sonarqube-data-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: {{ .Values.PersistentVolume.sonarqubeData.hostPath.path }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-logs-pv
  labels:
    app: sonarqube-logs-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: {{ .Values.PersistentVolume.sonarqubeLogs.hostPath.path }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extensions-pv
  labels:
    app: sonarqube-extensions-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: {{ .Values.PersistentVolume.sonarqubeExtensions.hostPath.path }}