apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-configmap
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
    exporters:
      otlp:
        endpoint: tempo-service:4317
        tls:
          insecure: true
      debug:
        verbosity: normal
      zipkin:
        endpoint: http://zipkin-service:9411/api/v2/spans
    service:
      pipelines:
        traces:
          receivers: [zipkin]
          processors: []
          exporters: [debug, otlp, zipkin]
