apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-home-pvc
spec:
  volumeName: superset-home-pv
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
