bluesky-project:
  nameOverride: bluesky-web-user
  image:
    artifactId: bluesky-web-user
  service:
    port: 30124
    nodePort: 30124
  ingress:
#    enabled: true
    hosts:
    - host: user.web.bluesky.local
      paths:
      - path: /
        pathType: Prefix