apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-deployment
  namespace: default
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: spring
          args:
            - '--spring.profiles.active={{ .Values.springProfilesActive }}'
            - '--spring.application.name={{ .Chart.Name }}'
          workingDir: /usr/local/app
          image: '{{ .Values.image.host }}/luversof/{{ .Values.image.artifactId}}:{{ .Values.image.buildVersion }}.{{ .Values.image.buildNumber }}'
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          ports:
            - name : http
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
