apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    spring-boot: true
  name: {{ .Chart.Name }}-service
  namespace: default
spec:
  ports:
    - name : http
      nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    app: {{ .Chart.Name }}
  type: NodePort