PersistentVolume:
  jenkinsDockerConfig:
    hostPath:
      path: /mnt/c/data/jenkins-docker
  jenkinsHome:
    hostPath:
      path: /mnt/c/data/jenkins-home
  jenkinsM2:
    hostPath:
      path: /mnt/c/data/jenkins-m2