bluesky-project:
  nameOverride: bluesky-api-bookkeeping
  image:
    artifactId: bluesky-api-bookkeeping
  service:
    port: 30130
    nodePort: 30130
  ingress:
    enabled: true
    hosts:
    - host: bookkeeping.api.bluesky.local
      paths:
      - path: /
        pathType: Prefix