apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-configmap
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100

    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo
          endpoint: seaweedfs-service:8333
          access_key: seaweedfs_access_key
          secret_key: seaweedfs_secret_key
          insecure: true
          forcepathstyle: true
          insecure: true
